version: '3'

services:

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    container_name: webshop-demo-mongodb

  api:
    build: ./packages/api
    ports:
      - 3001:3001
    depends_on:
      - mongodb
    volumes:
      - ./packages/api/src:/home/api/src
    container_name: webshop-demo-api

  client:
    build: ./packages/client
    ports:
      - 3000:3000
    volumes:
      - ./packages/client:/app
    container_name: webshop-demo-client
    stdin_open: true
